### PR TITLE
feature proposal: export_project()

### PR DESCRIPTION
**Pull request by brandmaier**
This adds a function that locally exports the project either to a new folder or to a zip drive. Whether the dataset will be included can be controlled by a function argument.

Also: adds a Makefile that simplifies building roxygen documentation, readme file, pkgdown website, build and install on macOS and Linux/Unix systems.

### CODE REVIEW

**Comment by cjvanlissa** [comment]
This is a fantastic addition, I immediately see the relevance for projects with collaborators who are not used to GitHub. Several notes:

* Unit tests on Travis are failing
* I got minor revisions from CRAN, and I don't have the time to incorporate this right before resubmitting - so let's put this in a separate branch until we can fix the unit tests
* I believe the robust way to get the file path to the project is by using `normalizePath(".")`
* If the functionality to export ZIP files respects the .gitIgnore files in the project, then we don't have to exclude specific files in the code. We can just find all .gitIgnore files, parse their contents, and exclude these files from the list-to-be-zipped

**Comment by cjvanlissa** [comment]
PS: the package `here` gives robust project locations, but I'd prefer to avoid incurring another dependency.

**Comment by brandmaier** [comment]
What about using:
rstudioapi::getActiveProject()
to determine the path of the current project?
Would you mind adding this dependency? This package could be useful for a lot of nice features, for example, writing Rstudio addins.

**Comment by cjvanlissa** [comment]
One more thought (can't find info on this): Maybe it's possible to link the `export_project()` function to the Build tab in RStudio? Just like bookdown, blogdown, etc, there could be a button to 'export' the project to send to collaborators

**Comment by brandmaier** [comment]
export_project() is now an Rstudio addin. By default, it exports a zip file with the project folder name in the directory the project folder exists.
Screenshot 2020-05-03 at 22 31 15

**Comment by cjvanlissa** [comment]
This thread mentions the `inconsolata.sty` problem on Travis: https://stackoverflow.com/questions/34524357/inconsolata-missing-to-build-r-vignette

If I understand correctly, solutions include: Install it in `_travis.yml`, or wait for Travis to update (or submit bug report)

**Comment by cjvanlissa** [comment]
It might be worth checking whether the `gert` package supports git archive, as this would cover some of the functionality of `export_project()` and would respect .gitIgnore files implicitly.

**Pull request merged**
