### PR TITLE
Fix test and docs for upcoming gert release

### PR DESCRIPTION
**Pull request by jeroen**
Hi! This fixes a few small issues needed for the upcoming release of gert 1.0. Could you try to get this on CRAN?

### CODE REVIEW

**Comment by cjvanlissa** [comment]
@jeroen will do, this is very kind.

**Comment by jeroen** [comment]
Awesome, can you let me know when you have submitted the new version to CRAN? Then I'll submit the new gert soon after that.

**Comment by cjvanlissa** [comment]
@jeroen yes, which `gert` version number should I require in the DESCRIPTION file?

**Comment by cjvanlissa** [comment]
Alternatively, this should maintain compatibility with old and new versions, correct?

```
if("remote" %in% formalArgs(git_remote_add)){
        git_remote_add(remote = "origin", url = remote_repo, repo = path)
      } else {
        git_remote_add(name = "origin", url = remote_repo, repo = path)
      }
```

**Comment by jeroen** [comment]
I decided to not change `git_remote_add` after all, to keep backward compatibility. So this new works should work both with the old and new version of gert.

**Comment by jeroen** [comment]
> Alternatively, this should maintain compatibility with old and new versions, correct?

Yes that works. I confirmed that your current version works with the current and upcoming version of gert.

**Comment by cjvanlissa** [comment]
@jeroen I'm waiting for one additional contributor to push a change, and will resubmit next Monday latest. Thank you so much for checking reverse compatibility!

**Pull request merged**
