### PR TITLE
added .worcs file to template

### PR DESCRIPTION
**Pull request by brandmaier**
This is how I envision a minimal .worcs file. This has information on which worcs specification the directory adheres to. Let's just call the current one 1.0. In future, the specification may likely change and it will incredibly useful to obtain this information in a standardized way.
We should also store, which package and version of the package created the repository. This may be useful to post-process or correct bugs that a given package or version of package may be notorious for.

### CODE REVIEW

**Comment by cjvanlissa** [comment]
I'm working on this now, so wait a few hours!

**Comment by brandmaier** [comment]
Fantastic! I will shut up.

**Comment by cjvanlissa** [comment]
I'm currently writing the following:

```
worcs_version: 0.1.1
creator: Sys.info()["effective_user"]
```

I don't think it's necessary to store the file type number of `.worcs`, because the filetype of .worcs is redundant with the package version, and package version is human-readable.

**Comment by brandmaier** [comment]
My thoughts were that package version is not necessarily identical to specification version because specs usually change much slower than package versions. But I also like your proposal because it favours simplicity.

**Comment by cjvanlissa** [comment]
Yes, but any spec change will be accompanied by a package change. So we can internally check if package version is > 0.1.1, e.g.

**Pull request closed without merging**
